Added React Native Blog and iot Image
meshhq/MeshWebsite pull request #53
Opened 2018-09-14 18:07 UTC by Reidweb1

2018-09-14 18:45 UTC, JohnDaly requested changes
Add links for the tooling

2018-09-14 19:25 UTC, JohnDaly commented on content/blog/2018-09-14-react-native-boilerplate.md
> +title: "React-Native Typescript Boilerplate"
React Native TypeScript Boilerplate

2018-09-14 19:26 UTC, JohnDaly commented on content/blog/2018-09-14-react-native-boilerplate.md
> +There are currently two ways to create a new React Native application;  `react-native-cli` and `create-react-native-app` (`CRNA`). We chose the former because it provides more flexibility when it com
a new React Native application:

Replace the ; with :

2018-09-14 19:30 UTC, JohnDaly commented on content/blog/2018-09-14-react-native-boilerplate.md
> +Note: Never edit Gradle files outside of Android Studio. It’s very easy to create build issues without taking advantage of the sync process embedded in Google’s IDE.
Maybe phrase this differently:

Note: We recommend that you only edit Gradle files with Android Studio. Google's IDE does a lot of Gradle-related work behind the scenes via a sync process, which makes it very easy to introduce build issues if you modify these files with a different program.

2018-09-14 19:34 UTC, JohnDaly commented on content/blog/2018-09-14-react-native-boilerplate.md
> +A Promise based HTTP client with TypeScript and React Native support. Allows a simple interface for clean HTTP requests and also allows automatic transforms for JSON data. Clean, simple, examples of
Provides a simple interface for clean HTTP requests, and also handles transforming JSON data for you

2018-09-14 22:13 UTC, JohnDaly approved these changes
LGTM

2018-09-14 22:13 UTC, merged

2018-09-17 17:18 UTC, tayhalla commented
@Reidweb1 and @JohnDaly just noticed this wasn't live on the site. We need to remember to run the compilation step `hugo`